name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: sudo apt-get install -y googletest
    - uses: actions/checkout@v2
    - name: Build the program
      run: |
        make test
        ./test_all
